### ISSUE TITLE
$print = false doesn't work ??

### ISSUE THREAD

**Issue by theperfectwill** [askupasoftware/wp-dynamic-css#4]
Hi. 

I meant to say this. In testing, I could never get this to work, neither with the latest update. 

I don't think I will be using it at all, but never the less I wanted to let you know. 

So for example... 

This works...

```
wp_dynamic_css_enqueue('user-generated-styles', '/my-path/css-user-generated.css');
```

and this doesn't output anything...

```
wp_dynamic_css_enqueue('user-generated-styles', '/my-path/css-user-generated.css', false);
```

Does it work for you? 

If so, maybe you can give me something to look into as to why it may not work with my setup? 

I'm in localhost using a custom theme, but other than than I only have a couple dev plugins that are not the issue.

**Comment by ykadosh** [comment]
When you set `$print` to false, the stylesheet is included externally instead of printed to the `<head>`. Are you not getting anything in the external stylesheet? In the head of your document, look for an external stylesheet that looks something like 

``` html
<link rel='stylesheet' id='wp-dynamic-css-css'  href='http://localhost/wp-admin/admin-ajax.php?action=wp_dynamic_css' type='text/css' media='all' />
```

**Comment by theperfectwill** [comment]
Exactly, that external stylesheet is not rendering. 

I can tell from the frontend because to test WP Dynamic Css I used `!important` on my styles and those styles only show when I remove false from the enqueue. 

I can also tell from the HTML source code, the stylesheet is not rendered at all.

**Comment by ykadosh** [comment]
Is there a way for me to access your site to see what's going on?

**Comment by theperfectwill** [comment]
No, I'm in localhost. It doesn't work for me as is, does it work for you? 

If it does then I will look more into my setup and theme what might be the problem.

**Comment by ykadosh** [comment]
Yes, it's working for me. I've tested it again just now. Does it not load the stylesheet, or does it load an empty one?

**Comment by theperfectwill** [comment]
Ok, I will look more into it. 

For me, it doesn't load the stylesheet. I'm resetting my computer, so I take a look shortly after I get things and localhost set back up.

**Comment by theperfectwill** [comment]
@ykadosh just updating. I haven't forgot about this and should be able to get to this near the end of this week or the beginning of the next. I started from scratch a bit on my theme so hopefully whatever the issue was won't be anymore. But I will return an update here to let you know. 

For now I closed this comment (I forgot it was open).

Thanks.
