### ISSUE TITLE
wp-dynamic-css gets overridden by styles generated from wp_enqueue_style

### ISSUE THREAD

**Issue by melchorc** [askupasoftware/wp-dynamic-css#7]
Here's my code on function.php. 
``
 function add_theme_styles() {
  $turi = get_template_directory_uri();
  wp_enqueue_style('font-awesome',$turi . '/css/font-awesome.min.css');
  wp_enqueue_style('bootstrap',$turi .'/css/bootstrap.css');
  wp_enqueue_style('star-rating',$turi .'/css/star-rating.min.css');
  wp_enqueue_style('slick',$turi .'/css/slick.css');
  wp_enqueue_style('ie10',$turi .'/css/ie10-viewport-bug-workaround.css');
  wp_enqueue_style('sitestyle',$turi .'/css/sitestyle.css');
}
add_action( 'wp_print_styles', 'add_theme_styles');
wp_dynamic_css_enqueue( 'site_theme',  get_template_directory_uri() . '/css/sitetheme.css', true, true);

```
It is generated from this order. 
 <style id="wp-dynamic-css"> .... </style>
<link rel='stylesheet' id='dashicons-css'  ... />
<link rel='stylesheet' id='admin-bar-css' .../>
<link rel='stylesheet' id='font-awesome-css' ... />
<link rel='stylesheet' id='bootstrap-css'  .../>
<link rel='stylesheet' id='star-rating-css' ... />
<link rel='stylesheet' id='slick-css' ... />
<link rel='stylesheet' id='ie10-css' .../>
<link rel='stylesheet' id='sitestyle-css' .../>

Setting add_action's priority does not work.
```

**Comment by melchorc** [comment]
I have this current workaround.
I've got it working by dequeuing wp-dynamic-css `wp_dequeue_style('wp-dynamic-css');`
and enqueuing it after with this code `wp_enqueue_style( 'wp-dynamic-css', admin_url( 'admin-ajax.php?action=wp_dynamic_css' ) );`

But I have to set the parameter $print to false to make it work.
`wp_dynamic_css_enqueue( 'site_theme',  get_template_directory_uri() . '/css/sitetheme.css', false, true);`

I hope this bug is fixed.

**Comment by ykadosh** [comment]
I don't think this is a bug. The second parameter to `wp_dynamic_css_enqueue()` needs to be the **path** to the stylesheet, not the URL. Try to change `get_template_directory_uri()` to `get_stylesheet_directory()`

## 

Upon reading your comment again, I think I see what you mean - you need to be able to set the priority of the stylesheet in the queue, correct?

**Comment by melchorc** [comment]
Yes. It has problems when it comes to setting stylesheet priority because I'm using your repository as WordPress Plugin. I think the issue is the plugin's style is enqueued first.

**Comment by ykadosh** [comment]
Since `wp_dynamic_css_enqueue()` may be called more than once, and all the calls are concatenated into a single CSS file, setting the priority in one call will override the priority in another call. Therefore, I've decided to hardcode a high priority (100) to allow the dynamically created CSS to override static styles.

**Comment by melchorc** [comment]
Thank u.
